repos:
- repo: https://github.com/golangci/golangci-lint
  rev: v1.52.2
  hooks:
  - id: golangci-lint
    name: golangci-lint
    description: Fast linters runner for Go.
    entry: golangci-lint run -D funlen -D bodyclose -D typecheck
    types: [go]
    language: golang
    pass_filenames: false

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.3.3
  hooks:
    - id: go-unit-tests

- repo: local
  hooks:
  - id: github-action-docs
    name: github-action-docs
    entry: make docs
    types: [yaml]
    pass_filenames: false
    language: system

# Repo doesn't have right permissions?
# - repo: https://github.com/launchdarkly/pre-commit-go
#   rev: v0.11.0
#   hooks:
#     - id: circleci-config-validate
#     - id: goimports
#     - id: compile-go-tests
#       entry: bin/run-script run-on-dirs "parallel -n 1 cd {} && env GO111MODULE=on go test -tags launchdarkly_easyjson,api_smoke_tests -c -o /dev/null :::"
#       exclude: '^vendor/|^.circleci/image/tools'
#     - id: go-mod-tidy
#     - id: go-mod-verify
#     - id: go-mod-vendor-no-change
#     - id: discarded-stacktrace
#       exclude: '(^vendor/|.*gen_.*.go)'
