# action.yml
name: 'Find Flags'
description: 'Find LaunchDarkly Flags in your Pull Request'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LD_PROJ_KEY: ${{ inputs.projKey }}
    LD_ACCESS_TOKEN: ${{ inputs.accessToken }}
    LD_BASE_URI: ${{ inputs.baseUri }}
    LD_ENV_KEY: ${{ inputs.envKey }}
    GITHUB_TOKEN: ${{ inputs.githubToken }}
    PLACEHOLDER_COMMENT: ${{ inputs.placeholderComment }}
inputs:
  projKey:
    description: 'LaunchDarkly Project'
    required: false
    default: 'default'
  envKey:
    description: 'LaunchDarkly Environment for Project. Can be a comma separated list of environment keys.'
    required: false
    default: 'production'
  baseUri:
    description: 'LaunchDarkly Instance'
    required: false
    default: 'https://app.launchdarkly.com'
  githubToken:
    description: 'Token to access your GitHub repository.'
    required: true
  accessToken:
    description: 'LaunchDarkly access token'
    required: true
  placeholderComment:
    description: 'Comment even if no flags are found. If flags are found in later commits this comment will be updated.'
    required: false
    default: 'true'
  maxFlags:
    description: 'Maximum number of flags to find per PR.'
    required: false
    default: '5'
