# action.yml
name: 'Find Flags'
description: 'Find LaunchDarkly Flags in your PR'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LD_PROJ_KEY: ${{ inputs.project-key }}
    LD_ACCESS_TOKEN: ${{ inputs.access-token }}
    LD_BASE_URI: ${{ inputs.base-uri }}
    LD_ENV_KEY: ${{ inputs.environment-key }}
    GITHUB_TOKEN: ${{ inputs.repo-token }}
inputs:
  repo-token:
      description: 'Token to use to authorize comments on PR. Typically the GITHUB_TOKEN secret.'
      required: true
  access-token:
    description: 'LaunchDarkly access token'
    required: true
  project-key:
    description: 'LaunchDarkly Project'
    required: false
    default: 'default'
  environment-key:
    description: 'LaunchDarkly environment for creating flag links'
    required: false
    default: 'production'
  placeholder-comment:
    description: 'Comment when no flags are found. If flags are found in later commits, this comment will be updated.'
    required: false
    default: 'false'
  include-archived-flags:
    description: 'Scan for archived flags'
    required: false
    default: 'true'
  max-flags:
    description: 'Maximum number of flags to find per PR'
    required: false
    default: '5'
  base-uri:
    description: 'The base URI for the LaunchDarkly server. Most users should use the default value.'
    required: false
    default: 'https://app.launchdarkly.com'

outputs:
  any-modified:
    description: Returns true if any flags have been added or modified in PR
  modified-flags:
    description: Space-separated list of flags added or modified in PR
  modified-flags-count:
    description: Number of flags added or modified in PR
  any-removed:
    description: Returns true if any flags have been removed in PR
  removed-flags:
    description: Space-separated list of flags removed in PR
  removed-flags-count:
    description: Number of flags removed in PR
