# action.yml
name: 'Find Flags'
description: 'Find LaunchDarkly Flags in your Pull Request'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LD_PROJ_KEY: ${{ inputs.project-key }}
    LD_ACCESS_TOKEN: ${{ inputs.access-token }}
    LD_BASE_URI: ${{ inputs.base-uri }}
    LD_ENV_KEY: ${{ inputs.environment-key }}
    GITHUB_TOKEN: ${{ inputs.repo-token }}
inputs:
  project-key:
    description: 'LaunchDarkly Project'
    required: false
    default: 'default'
  environment-key:
    description: 'LaunchDarkly environment for setting flag links. Can be a comma-separated list of environment keys.'
    required: false
    default: 'production'
  base-uri:
    description: 'The base URI for the LaunchDarkly server. Most users should use the default value.'
    required: false
    default: 'https://app.launchdarkly.com'
  repo-token:
    description: 'Token to use to authorize comments on PR. Typically the GITHUB_TOKEN secret.'
    required: true
  access-token:
    description: 'LaunchDarkly access token'
    required: true
  placeholder-comment:
    description: 'Comment even if no flags are found. If flags are found in later commits this comment will be updated.'
    required: false
    default: 'false'
  max-flags:
    description: 'Maximum number of flags to find per PR'
    required: false
    default: '5'

outputs:
  any_modified:
    description: Returns true if any flags have been added or modified in pull request
  modified_flags:
    description: Space-separated list of flags added or modified in pull request
  modified_flags_count:
    description: Number of flags added or modified in pull request
  any_removed:
    description: Returns true if any flags have been removed in pull request
  removed_flags:
    description: Space-separated list of flags removed in pull request
  removed_flags_count:
    description: Number of flags removed in pull request
